---
title: 十二铁COMBO列表
author:
  - Facet
date: "最后编辑于 `r format(Sys.time(), '%H:%M, %d %B, %Y')`"
output:
  bookdown::html_document2:
    toc: true
    latex_engine: xelatex
    keep_tex: true
    number_sections: false
---


::: {.remark}

<br>

1. 命名方式: (克拉斯)+(纳贝尔/姬特)+(人马)+(十二兽)+(兽)+(天玑)+(抗战)


1. 纳贝尔单独出现时可以被姬特替代, 反之不亦然.

1. 终场中如果没有龙枪, 十二兽可以先叠虎炮而不是猪弓, 保留猪弓天霆号的combo.

1. 天玑可以被十二兽+强贪或任意可以被炸的卡替代.

1. 有天玑找十二兽的场合有足够的素材阴间link凶鸟, 因此可以拿到兽启动克拉斯, 故多一张兽不会有新的combo, 但如果带了乌鸦可以多一张乌鸦.

1. 纳贝尔和人马一起出现时暂无新的combo, 即其中一张在combo中退化为铁兽.

:::

# 一卡

### 十二兽

1.通招十二兽，十二兽叠猪弓，猪弓叠虎炮，虎炮叠龙枪

终场：

龙枪+4手


::: {.remark}

<br>

- 即使龙枪被解，可以在墓地凑够4兽，为之后抽到铁兽或抗战做准备

- 对于十二兽+克拉斯，十二兽+纳贝尔，十二兽+姬特的牌型，建议同样是做龙枪过，十二兽+人马可以考虑[人马+兽]

:::



### 纳贝尔

1.通招纳贝尔，纳贝尔链接独角兔，发纳贝尔拿人马

终场：

独角兔+5手


::: {.remark}

<br>

- 纳贝尔没必要盖，在场上可能被对方除外，如果没被对方打进墓的话，还会少赚卡

:::



### 人马

1. 发人马扔姬特，发姬特扔纳贝尔，发纳贝尔拿人马

2. 通招人马，发人马特招块击

3. 人马块击链接银弹，发块击拿抗战

终场：

银弹+抗战+3手

# 两卡

### 纳贝尔+天玑

1. 发天玑拿羊冲，通招羊冲，羊冲叠猪弓，猪弓叠龙枪

2. 发龙枪炸天玑，龙枪叠狗环，发狗环特招龙枪

3. 狗环龙枪链接徒花，发徒花特招纳贝尔

4. 发纳贝尔特招凶鸟，纳贝尔凶鸟链接块击，发纳贝尔拿克拉斯，发凶鸟拿马剑

5. 特招克拉斯扔马剑，发克拉斯特招双龙

6. 克拉斯徒花块击链接神弓，发块击拿抗战

终场：

2400神弓+双龙+抗战+2手


### 人马+兽

1. 发人马扔姬特，发姬特扔纳贝尔，发纳贝尔拿克拉斯

2. 特招克拉斯扔兽，发克拉斯特招凶鸟

3. 克拉斯凶鸟链接徒花(块击)，发凶鸟拿人马

4. 发徒花特招人马(通招人马)，发人马特招块击(徒花)

5. 人马徒花块击链接神弓，发块击拿抗战

终场：

2400神弓+抗战+2手


::: {.remark}

可以多花一张卡多做一个双龙:

1. 发人马扔姬特，发姬特扔纳贝尔，发纳贝尔拿人马

2. 通招人马，发人马特招块击

3. 发块击扔兽特招姬特，发姬特特招双龙

4. 人马姬特块击链接神弓，发块击拿抗战



:::



### 人马+铁兽

1. 发人马扔姬特，发姬特扔纳贝尔，发纳贝尔拿姬特

2. 通招姬特，发姬特特招徒花

3. 发徒花特招铁兽，
4. 姬特链接独角兔，发独角兔.  
   或,姬特徒花链接银弹。

4. 发铁兽特招块击，铁兽徒花(银弹)块击链接神弓，发块击拿抗战

终场：

2400神弓+抗战+2手




### 克拉斯+纳贝尔

1. 特招克拉斯扔纳贝尔，发纳贝尔拿人马，发人马扔姬特，发姬特扔人马

2. 发克拉斯特招凶鸟，克拉斯凶鸟链接徒花，发凶鸟拿人马

3. 发徒花特招人马，发人马特招块击

4. 人马徒花块击链接神弓，发块击拿抗战

终场：

2400神弓+抗战+2手

### 克拉斯+姬特：

1. 特招克拉斯扔姬特，发姬特扔纳贝尔，发纳贝尔拿人马

2. 通招人马，发人马特招块击，发人马扔姬特

3. 发克拉斯特招徒花，克拉斯徒花块击链接神弓，发块击拿抗战

终场：

2400神弓+抗战+2手


::: {.remark}

<br>

- 和[克拉斯+纳贝尔]类似，区别在于，[克拉斯+纳贝尔]：6招出神弓，徒花正规出场，这里5招内出神弓，省下凶鸟

:::



### 人马+天玑

1. 发天玑拿羊冲，通招羊冲，羊冲叠猪弓，猪弓叠龙枪

2. 发龙枪炸天玑，龙枪叠狗环，发狗环特招龙枪

3. 狗环龙枪链接徒花，发徒花特招人马

4. 发人马招块击, 发人马扔姬特，发姬特扔纳贝尔，发纳贝尔拿铁兽

5. 块击徒花链接神弓, 发块击拿抗战.

终场：

1600神弓+抗战+3手


::: {.remark}

<br>

- 可以让神弓多一素材少一张牌: 

    1. 发天玑拿羊冲，通招羊冲，羊冲叠猪弓，猪弓叠龙枪

    2. 发龙枪炸天玑，龙枪叠狗环，发狗环特招龙枪

    3. 狗环龙枪链接徒花，发徒花特招人马

    4. 发人马特招凶鸟，发人马扔姬特，发姬特扔纳贝尔，发纳贝尔拿克拉斯

    5. 徒花凶鸟链接银弹，发凶鸟拿马剑

    6. 特招克拉斯扔马剑，发克拉斯特招块击

    7. 克拉斯块击银弹链接神弓，发块击拿抗战

:::


### 十二兽+天玑:

天玑拿人马, 后同[人马+天玑]



### 铁兽+天玑

1. 发天玑拿羊冲，通招羊冲，羊冲叠猪弓，猪弓叠龙枪

2. 发龙枪炸天玑，龙枪叠狗环，发狗环特招龙枪

3. 狗环龙枪链接徒花，发徒花特招铁兽

4. 发铁兽特招凶鸟，铁兽凶鸟链接块击

1. 徒花块击链接神弓，发块击拿抗战

终场：

1600神弓+抗战+3手


::: {.remark}

可以少一张手牌做2400神弓:

第四步改为发铁兽特招块击，铁兽徒花块击链接神弓，发块击拿抗战

:::


### 纳贝尔+兽

1. 通招纳贝尔，纳贝尔链接独角兔，发纳贝尔拿克拉斯

2. 特招克拉斯扔兽，发克拉斯特招块击

3. 克拉斯块击链接银弹，发块击拿抗战

终场：

独角兔+银弹+抗战+2手
 

### 人马+抗战：

1. 发人马扔姬特，发姬特扔纳贝尔，发纳贝尔拿人马

2. 通招人马，发人马特招银弹，人马银弹链接神弓

终场：

1600神弓+抗战+3手



### 纳贝尔+抗战：

1. 通招纳贝尔，纳贝尔链接独角兔，发纳贝尔拿人马

2. 发人马扔姬特，发姬特扔人马

终场：

独角兔+抗战+3手

 
# 三卡

### 克拉斯+姬特+天玑

1. 发天玑拿羊冲，通招羊冲，羊冲叠猪弓，猪弓叠龙枪

2. 发龙枪炸天玑，龙枪叠狗环，发狗环特招龙枪，狗环叠虎炮，发虎炮选龙枪

3. 特招克拉斯扔姬特，发姬特扔纳贝尔，发纳贝尔拿人马

4. 发克拉斯特招双龙，克拉斯虎炮链接徒花

5. 发徒花特招人马，发人马特招凶鸟

6. 人马凶鸟链接块击，徒花块击链接神弓，发块击拿抗战

终场：

1600神弓+龙枪+双龙+抗战+2手

### 克拉斯+人马+天玑

同[克拉斯+兽+天玑]

::: {.remark}

<br>

如果带了DD乌鸦可以让神弓少一个素材抓上来


1. 发天玑拿羊冲，通招羊冲，羊冲叠猪弓，猪弓叠龙枪

2. 发龙枪炸天玑，龙枪叠狗环，发狗环特招龙枪

3. 狗环龙枪链接徒花，发徒花特招人马

4. 发人马特招凶鸟，发人马扔姬特，发姬特扔纳贝尔，发纳贝尔拿铁兽

6. 特招克拉斯扔铁兽特招双龙

7. 克拉斯凶鸟链接块击, 发凶鸟拿牌

5. 徒花块击克拉斯链接神弓，发块击拿抗战


:::

### 克拉斯+兽+天玑


1. 发天玑拿羊冲，通招羊冲，羊冲叠猪弓，猪弓叠龙枪

2. 发龙枪炸天玑，龙枪叠狗环，发狗环特招龙枪

3. 狗环龙枪链接徒花

1. 克拉斯扔兽特招, 发效拉凶鸟.

1. 凶鸟克拉斯链接块击, 凶鸟拿姬特

1. 徒花发效拉姬特, 发姬特拉双龙.

1. 徒花块击姬特链接神弓, 姬特扔纳贝尔, 块击拿抗战.

终场：

2400神弓+双龙+抗战+2手

### 克拉斯+姬特+十二兽

1. 通招十二兽，十二兽叠猪弓，猪弓叠龙枪

2. 特招克拉斯扔姬特，发姬特扔纳贝尔，发纳贝尔拿人马

3. 发克拉斯特招徒花，发龙枪炸克拉斯

4. 龙枪叠狗环，发狗环特招龙枪，狗环叠虎炮，发虎炮选龙枪

5. 发徒花特招人马，发人马特招凶鸟

6. 人马凶鸟链接块击，虎炮徒花块击链接神弓，发块击拿抗战

终场：

2400神弓+龙枪+抗战+2手

### 克拉斯+人马+十二兽

同[人马+十二兽+兽]
 
### 人马+铁兽+兽

1. 发人马扔姬特，发姬特扔纳贝尔，发纳贝尔拿克拉斯

2. 特招克拉斯扔兽，发克拉斯特招凶鸟

3. 克拉斯凶鸟链接徒花，发凶鸟拿羊冲

4. 发徒花特招铁兽，发铁兽特招块击

5. 通招羊冲，羊冲叠猪弓，猪弓叠龙枪

5. 铁兽徒花块击链接神弓，发块击拿抗战

终场：

2400神弓+龙枪+抗战+1手


::: {.remark}


可以换成[人马+兽]

:::



### 人马+十二兽+兽

1. 通招十二兽，十二兽叠猪弓，猪弓叠龙枪

2. 发人马扔姬特，发姬特扔纳贝尔，发纳贝尔拿克拉斯

3. 特招克拉斯扔兽，发克拉斯特招凶鸟

4. 克拉斯凶鸟链接徒花，发凶鸟拿人马

5. 发徒花特招人马，发人马特招块击

6. 人马徒花块击链接神弓，发块击拿抗战

终场：

2400神弓+龙枪+抗战+1手


::: {.remark}

可以换成[人马+兽]

:::



### 克拉斯+纳贝尔+铁兽

1. 特招克拉斯扔纳贝尔，发纳贝尔拿人马，发人马扔姬特，发姬特扔人马

2. 发克拉斯特招凶鸟，克拉斯凶鸟链接徒花，发凶鸟拿羊冲

4. 发徒花特招铁兽，发铁兽特招块击

5. 通招羊冲，羊冲叠猪弓，猪弓叠龙枪

5. 铁兽徒花块击链接神弓，发块击拿抗战

终场：

2400神弓+龙枪+抗战+1手

1.可以换成[克拉斯+纳贝尔]，用小一点的场换多1坑，或留怪为下回合做准备


### 克拉斯+纳贝尔+十二兽

1. 通招十二兽，十二兽叠猪弓，猪弓叠龙枪

2. 特招克拉斯扔纳贝尔，发纳贝尔拿人马，发人马扔姬特，发姬特扔人马

3. 发克拉斯特招凶鸟，克拉斯凶鸟链接徒花，发凶鸟拿人马

4. 发徒花特招人马，发人马特招块击

5. 人马徒花块击链接神弓，发块击拿抗战

终场：

2400神弓+龙枪+抗战+1手

1.可以换成[克拉斯+纳贝尔]，用小一点的场换多1坑，或留怪为下回合做准备

### 马剑+羊冲+铁兽

1. 通招马剑扔羊冲，马剑叠猪弓，猪弓叠狗环

2. 发狗环特招羊冲，狗环叠龙枪

3. 发龙枪炸羊冲，发羊冲特招狗环

4. 龙枪叠虎炮，发虎炮指狗环，发狗环特招龙枪

5. 狗环虎炮链接徒花，发徒花特招铁兽

6. 发铁兽特招凶鸟，铁兽凶鸟链接块击，发凶鸟拿蛇笞

7. 徒花块击链接神弓，发块击拿抗战，发蛇笞选龙枪

终场：

1600神弓+龙枪+抗战+2手



### 克拉斯+纳贝尔+天玑

1. 发天玑拿羊冲，通招羊冲，羊冲叠猪弓，猪弓叠龙枪

2. 发龙枪炸天玑，龙枪叠狗环，发狗环特招龙枪，狗环叠虎炮，发虎炮选龙枪

3. 特招克拉斯扔纳贝尔，发纳贝尔拿姬特

4. 发纳贝尔特招双龙，纳贝尔虎炮链接徒花

5. 发徒花特招姬特，发姬特特招块击

6. 姬特徒花块击链接神弓，发块击拿抗战

终场：

2400神弓+龙枪+双龙+抗战+1手


::: {.remark}

<br>

- 有对象给龙枪炸卡可以启动十二兽展开，对比[克拉斯+纳贝尔+十二兽]的终场，相当于白嫖了双龙

:::


### 人马+铁兽+兽：

1. 发人马扔姬特，发姬特扔纳贝尔，发纳贝尔拿克拉斯

2. 通招铁兽，发铁兽特招块击

3. 特招克拉斯扔兽，发克拉斯特招双龙

4. 铁兽克拉斯块击链接神弓，发块击拿抗战

终场：

2400神弓+双龙+抗战+1手


### 人马+铁兽+抗战：

1. 发人马扔姬特，发姬特扔纳贝尔，发纳贝尔拿人马

2. 通招人马，发人马特招徒花

3. 发徒花特招铁兽，人马徒花链接银弹

4. 发铁兽特招双龙，铁兽银弹链接神弓

终场：

1600神弓+双龙+抗战+2手


### 人马+天玑+抗战

1. 发天玑拿羊冲，通招羊冲，羊冲叠猪弓，猪弓叠龙枪

2. 发龙枪炸天玑，龙枪叠狗环，发狗环特招龙枪

3. 狗环龙枪链接徒花，发徒花特招人马

4. 发人马特招凶鸟，发人马扔姬特，发姬特扔纳贝尔，发纳贝尔拿克拉斯

5. 徒花凶鸟链接银弹，发凶鸟拿马剑

6. 特招克拉斯扔马剑，发克拉斯特招双龙，克拉斯银弹链接神弓

终场：

1600神弓+双龙+抗战+2手

### 十二兽+天玑+抗战

天玑拿人马, 后同[人马+天玑+抗战].


### 纳贝尔+天玑+抗战

1. 发天玑拿羊冲，通招羊冲，羊冲叠猪弓，猪弓叠龙枪

2. 发龙枪炸天玑，龙枪叠狗环，发狗环特招龙枪

3. 狗环龙枪链接徒花，发徒花特招纳贝尔

4. 发纳贝尔特招凶鸟

5. 徒花凶鸟纳贝尔链接神弓，发凶鸟拿马剑, 纳贝尔拿克拉斯

7. 特招克拉斯扔马剑，发克拉斯特招双龙

终场：

2400神弓+双龙+抗战+克拉斯+2手

 
# 四卡

### 纳贝尔+马剑+羊冲+兽

1. 通招马剑扔羊冲，马剑叠猪弓，猪弓叠狗环

2. 发狗环特招羊冲，狗环叠龙枪

3. 发龙枪炸羊冲，发羊冲特招狗环

4. 龙枪叠虎炮，发虎炮指狗环，发狗环特招龙枪

5. 狗环虎炮链接徒花，发徒花特招纳贝尔

6. 发纳贝尔特招凶鸟，纳贝尔凶鸟链接块击，发纳贝尔拿克拉斯，发凶鸟拿蛇笞

7. 特招克拉斯扔兽，发克拉斯特招双龙

8. 克拉斯徒花块击链接神弓，发块击拿抗战，发蛇笞选龙枪

终场：

2400神弓+龙枪+双龙+抗战+1手

### 克拉斯+姬特+十二兽+抗战

1. 通招十二兽，十二兽叠猪弓，猪弓叠龙枪

2. 特招克拉斯扔姬特，发姬特扔纳贝尔，发纳贝尔拿人马

3. 发克拉斯特招徒花，发龙枪炸克拉斯

4. 龙枪叠狗环，发狗环特招龙枪，狗环叠虎炮，发虎炮选龙枪

5. 发徒花特招人马，发人马特招双龙，人马虎炮徒花链接神弓

终场：

2400神弓+龙枪+双龙+抗战+1手

### 克拉斯+十二兽+羊冲+铁兽

1. 特招克拉斯扔羊冲

2. 通招十二兽，十二兽叠猪弓，猪弓叠狗环

3. 发狗环特招羊冲，狗环叠龙枪

4. 发龙枪炸羊冲，发羊冲特招狗环

5. 发克拉斯特招块击，克拉斯狗环链接徒花

6. 发徒花特招铁兽，发铁兽特招双龙，铁兽块击徒花链接神弓

终场：

2400神弓+龙枪+双龙+抗战+1手

::: {.remark}

<br>

(ref)[https://ngabbs.com/read.php?&tid=31103283&pid=596479936&to=1k]

:::

 

# 五卡

### 纳贝尔+马剑+羊冲+兽+抗战

1. 通招马剑扔羊冲，马剑叠猪弓，猪弓叠狗环

2. 发狗环特招羊冲，狗环叠龙枪

3. 发龙枪炸羊冲，发羊冲特招狗环  

4. 龙枪叠虎炮，发虎炮指狗环，发狗环特招龙枪

5. 狗环虎炮链接徒花，发徒花特招纳贝尔

6. 发纳贝尔特招凶鸟，纳贝尔徒花凶鸟链接神弓，发纳贝尔拿克拉斯，发凶鸟拿蛇笞

7. 特招克拉斯扔兽，发克拉斯特招双龙，发蛇笞选龙枪

终场：

2400神弓+龙枪+双龙+克拉斯+抗战+1手


::: {.remark}

<br>

- 纳贝尔姬特徒花特招凶鸟需要三个格子, 因此抗战前需要先启动双龙送掉克拉斯.



:::

