---
title: HW 2
author:
  - Xie zejian
date: "Last compiled on `r format(Sys.time(), '%H:%M, %d %B, %Y')`"
output:
  bookdown::html_document2:
    toc: true
    latex_engine: xelatex
    keep_tex: true
    number_sections: false
---

# 1

### combo30.十二兽：

1.通招十二兽，十二兽叠猪弓，猪弓叠虎炮，虎炮叠龙枪

终场：

龙枪+4手

1.即使龙枪被解，可以在墓地凑够4兽，为之后抽到铁兽或抗战做准备

2.对于十二兽+克拉斯，十二兽+纳贝尔，十二兽+姬特的牌型，建议同样是做龙枪过，十二兽+人马可以考虑combo19



### combo31.纳贝尔：

1.通招纳贝尔，纳贝尔链接独角兔，发纳贝尔拿人马

终场：

独角兔+5手

1.纳贝尔没必要盖，在场上可能被对方除外，如果没被对方打进墓的话，还会少赚卡



### combo32.克拉斯：

终场：

5手

1.全靠其它坑的质量

### combo27.人马+1手：

1.发人马扔姬特，发姬特扔纳贝尔，发纳贝尔拿人马

2.通招人马，发人马特招块击

3.人马块击链接银弹，发块击拿抗战

终场：

银弹+抗战+3手

# 2

### ☆combo12.纳贝尔+天玑：

1.发天玑拿羊冲，通招羊冲，羊冲叠猪弓，猪弓叠龙枪

2.发龙枪炸天玑，龙枪叠狗环，发狗环特招龙枪

3.狗环龙枪链接徒花，发徒花特招纳贝尔

4.发纳贝尔特招凶鸟，纳贝尔凶鸟链接块击，发纳贝尔拿克拉斯，发凶鸟拿马剑

5.特招克拉斯扔马剑，发克拉斯特招双龙

6.克拉斯徒花块击链接神弓，发块击拿抗战

终场：

2400神弓+双龙+抗战+2手

1.最经典的十二兽起手

### ☆combo13.人马+兽+2手：

1.发人马扔姬特，发姬特扔纳贝尔，发纳贝尔拿人马

2.通招人马，发人马特招块击

3.发块击扔兽特招姬特，发姬特特招双龙

4.人马姬特块击链接神弓，发块击拿抗战

终场：

2400神弓+双龙+抗战+1手


### ☆combo19.人马+兽+1手：

1.发人马扔姬特，发姬特扔纳贝尔，发纳贝尔拿克拉斯

2.特招克拉斯扔兽，发克拉斯特招凶鸟

3.克拉斯凶鸟链接徒花，发凶鸟拿人马

4.发徒花特招人马，发人马特招块击

5.人马徒花块击链接神弓，发块击拿抗战

终场：

2400神弓+抗战+2手

1.最经典的铁兽起手

2.第3步可以改成：克拉斯凶鸟链接块击，发凶鸟拿人马。然后第4步改成：通招人马，发人马特招徒花



### combo20.人马+铁兽+1手：

1.发人马扔姬特，发姬特扔纳贝尔，发纳贝尔拿姬特

2.通招姬特，发姬特特招徒花

3.发徒花特招铁兽，姬特链接独角兔，发独角兔

4.发铁兽特招块击，铁兽徒花块击链接神弓，发块击拿抗战

终场：

2400神弓+抗战+2手

1.相比combo19，省下凶鸟

2.第3步可以改成：发徒花特招铁兽，姬特徒花链接银弹。然后第4步改成：发铁兽特招块击，铁兽块击银弹链接神弓，发块击拿抗战



### ☆combo21.铁兽+天玑+1手：

1.发天玑拿羊冲，通招羊冲，羊冲叠猪弓，猪弓叠龙枪

2.发龙枪炸天玑，龙枪叠狗环，发狗环特招龙枪

3.狗环龙枪链接徒花，发徒花特招铁兽

4.发铁兽特招块击，铁兽徒花块击链接神弓，发块击拿抗战

终场：

2400神弓+抗战+2手

1.对比combo25，相似的场却可以多留1手

2.如果铁兽是纳贝尔或姬特，还可以再多赚1手



### ☆combo22.克拉斯+纳贝尔+1手：

1.特招克拉斯扔纳贝尔，发纳贝尔拿人马，发人马扔姬特，发姬特扔人马

2.发克拉斯特招凶鸟，克拉斯凶鸟链接徒花，发凶鸟拿人马

3.发徒花特招人马，发人马特招块击

4.人马徒花块击链接神弓，发块击拿抗战

终场：

2400神弓+抗战+2手



### combo23.人马+天玑+1手：

1.发天玑拿羊冲，通招羊冲，羊冲叠猪弓，猪弓叠龙枪

2.发龙枪炸天玑，龙枪叠狗环，发狗环特招龙枪

3.狗环龙枪链接徒花，发徒花特招人马

4.发人马特招凶鸟，发人马扔姬特，发姬特扔纳贝尔，发纳贝尔拿克拉斯

5.徒花凶鸟链接银弹，发凶鸟拿马剑

6.特招克拉斯扔马剑，发克拉斯特招块击

7.克拉斯块击银弹链接神弓，发块击拿抗战

终场：

2400神弓+抗战+2手

1.相比combo21，多用掉了链接怪资源，但是多积累了墓地资源，多滤了牌。

### 十二兽+天玑+1手:

天玑拿人马, 后同combo23


### ☆combo24.克拉斯+姬特+1手：

1.特招克拉斯扔姬特，发姬特扔纳贝尔，发纳贝尔拿人马

2.通招人马，发人马特招块击，发人马扔姬特

3.发克拉斯特招徒花，克拉斯徒花块击链接神弓，发块击拿抗战

终场：

2400神弓+抗战+2手

1.和combo22类似，区别在于，combo22：6招出神弓，徒花正规出场，combo24：5招内出神弓，省下凶鸟



### ☆combo25.铁兽+天玑：

1.发天玑拿羊冲，通招羊冲，羊冲叠猪弓，猪弓叠龙枪

2.发龙枪炸天玑，龙枪叠狗环，发狗环特招龙枪

3.狗环龙枪链接徒花，发徒花特招铁兽

4.发铁兽特招凶鸟，铁兽凶鸟链接块击

6徒花块击链接神弓，发块击拿抗战

终场：

1600神弓+抗战+3手

1.如果铁兽是纳贝尔或姬特，还可以再多赚1手

 

### combo26.人马+抗战：

1.发人马扔姬特，发姬特扔纳贝尔，发纳贝尔拿人马

2.通招人马，发人马特招银弹，人马银弹链接神弓

终场：

1600神弓+抗战+3手

### combo28.纳贝尔+兽+1手：

1.通招纳贝尔，纳贝尔链接独角兔，发纳贝尔拿克拉斯

2.特招克拉斯扔兽，发克拉斯特招块击

3.克拉斯块击链接银弹，发块击拿抗战

终场：

独角兔+银弹+抗战+2手

1.通常是纳贝尔+纳贝尔，纳贝尔+姬特，或姬特+姬特时选择这种做法

 

### combo29.纳贝尔+抗战：

1.通招纳贝尔，纳贝尔链接独角兔，发纳贝尔拿人马

2.发人马扔姬特，发姬特扔人马

终场：

独角兔+抗战+3手

1.在墓地凑够4兽

 
# 3 

### ☆combo5.克拉斯+姬特+天玑：

1.发天玑拿羊冲，通招羊冲，羊冲叠猪弓，猪弓叠龙枪

2.发龙枪炸天玑，龙枪叠狗环，发狗环特招龙枪，狗环叠虎炮，发虎炮选龙枪

3.特招克拉斯扔姬特，发姬特扔纳贝尔，发纳贝尔拿人马

4.发克拉斯特招双龙，克拉斯虎炮链接徒花

5.发徒花特招人马，发人马特招凶鸟

6.人马凶鸟链接块击，徒花块击链接神弓，发块击拿抗战

终场：

1600神弓+龙枪+双龙+抗战+2手

### 克拉斯+人马+天玑：

1.发天玑拿羊冲，通招羊冲，羊冲叠猪弓，猪弓叠龙枪

2.发龙枪炸天玑，龙枪叠狗环，发狗环特招龙枪

3.狗环龙枪链接徒花，发徒花特招人马

4. 发人马特招块击，发人马扔姬特，发姬特扔纳贝尔，发纳贝尔拿铁兽

6.特招克拉斯扔铁兽特招双龙

5.徒花块击克拉斯链接神弓，发凶鸟拿马剑

7.克拉斯块击银弹链接神弓，发块击拿抗战

终场：

2400神弓+双龙+抗战+1手


::: {.remark}

<br>

- 也可做1600神弓+双龙+抗战+2手, 人马发效招凶鸟, 然后凶鸟和克拉斯链接块击

:::





### ☆combo6.克拉斯+姬特+十二兽：

1.通招十二兽，十二兽叠猪弓，猪弓叠龙枪

2.特招克拉斯扔姬特，发姬特扔纳贝尔，发纳贝尔拿人马

3.发克拉斯特招徒花，发龙枪炸克拉斯

4.龙枪叠狗环，发狗环特招龙枪，狗环叠虎炮，发虎炮选龙枪

5.发徒花特招人马，发人马特招凶鸟

6.人马凶鸟链接块击，虎炮徒花块击链接神弓，发块击拿抗战

终场：

2400神弓+龙枪+抗战+2手

1.发克拉斯效果时，如果克拉斯被效遮泡影，连锁龙枪炸克拉斯可保效果通过

2.即使克拉斯没被无效，炸掉克拉斯可以丰富墓地资源，并启动十二兽的展开

 
### combo7.人马+铁兽+兽+1手：

1.发人马扔姬特，发姬特扔纳贝尔，发纳贝尔拿克拉斯

2.特招克拉斯扔兽，发克拉斯特招凶鸟

3.克拉斯凶鸟链接徒花，发凶鸟拿羊冲

4.发徒花特招铁兽，发铁兽特招块击

5.通招羊冲，羊冲叠猪弓，猪弓叠龙枪

5.铁兽徒花块击链接神弓，发块击拿抗战

终场：

2400神弓+龙枪+抗战+1手

1.可以换成combo19，用小一点的场换多1坑，或留怪为下回合做准备


### combo8.人马+十二兽+兽+1手：

1.通招十二兽，十二兽叠猪弓，猪弓叠龙枪

2.发人马扔姬特，发姬特扔纳贝尔，发纳贝尔拿克拉斯

3.特招克拉斯扔兽，发克拉斯特招凶鸟

4.克拉斯凶鸟链接徒花，发凶鸟拿人马

5.发徒花特招人马，发人马特招块击

6.人马徒花块击链接神弓，发块击拿抗战

终场：

2400神弓+龙枪+抗战+1手

1.可以换成combo19，用小一点的场换多1坑，或留怪为下回合做准备


### combo9.克拉斯+纳贝尔+铁兽+1手：

1.特招克拉斯扔纳贝尔，发纳贝尔拿人马，发人马扔姬特，发姬特扔人马

2.发克拉斯特招凶鸟，克拉斯凶鸟链接徒花，发凶鸟拿羊冲

4.发徒花特招铁兽，发铁兽特招块击

5.通招羊冲，羊冲叠猪弓，猪弓叠龙枪

5.铁兽徒花块击链接神弓，发块击拿抗战

终场：

2400神弓+龙枪+抗战+1手

1.可以换成combo22，用小一点的场换多1坑，或留怪为下回合做准备


### combo10.克拉斯+纳贝尔+十二兽+1手：

1.通招十二兽，十二兽叠猪弓，猪弓叠龙枪

2.特招克拉斯扔纳贝尔，发纳贝尔拿人马，发人马扔姬特，发姬特扔人马

3.发克拉斯特招凶鸟，克拉斯凶鸟链接徒花，发凶鸟拿人马

4.发徒花特招人马，发人马特招块击

5.人马徒花块击链接神弓，发块击拿抗战

终场：

2400神弓+龙枪+抗战+1手

1.可以换成combo22，用小一点的场换多1坑，或留怪为下回合做准备

### ☆combo11.马剑+羊冲+铁兽：

1.通招马剑扔羊冲，马剑叠猪弓，猪弓叠狗环

2.发狗环特招羊冲，狗环叠龙枪

3.发龙枪炸羊冲，发羊冲特招狗环

4.龙枪叠虎炮，发虎炮指狗环，发狗环特招龙枪

5.狗环虎炮链接徒花，发徒花特招铁兽

6.发铁兽特招凶鸟，铁兽凶鸟链接块击，发凶鸟拿蛇笞

7.徒花块击链接神弓，发块击拿抗战，发蛇笞选龙枪

终场：

1600神弓+龙枪+抗战+2手

1.如果铁兽是纳贝尔或姬特，还可以再多赚1手



### ☆combo2.克拉斯+纳贝尔+天玑+1手：

1.发天玑拿羊冲，通招羊冲，羊冲叠猪弓，猪弓叠龙枪

2.发龙枪炸天玑，龙枪叠狗环，发狗环特招龙枪，狗环叠虎炮，发虎炮选龙枪

3.特招克拉斯扔纳贝尔，发纳贝尔拿姬特

4.发纳贝尔特招双龙，纳贝尔虎炮链接徒花

5.发徒花特招姬特，发姬特特招块击

6.姬特徒花块击链接神弓，发块击拿抗战

终场：

2400神弓+龙枪+双龙+抗战+1手

1.有对象给龙枪炸卡可以启动十二兽展开，对比combo10的终场，相当于白嫖了双龙

### combo16.克拉斯+纳贝尔+3手：

1.特招克拉斯扔纳贝尔，发纳贝尔拿人马，发人马扔姬特，发姬特扔人马

2.发克拉斯特招块击，发块击特招人马，发人马特招双龙

3.克拉斯人马块击链接神弓，发块击拿抗战

终场：

2400神弓+双龙+抗战

1.打空手牌的做法，如果手牌质量好不建议使用，可换成combo22

### combo14.人马+铁兽+兽+1手：

1.发人马扔姬特，发姬特扔纳贝尔，发纳贝尔拿克拉斯

2.通招铁兽，发铁兽特招块击

3.特招克拉斯扔兽，发克拉斯特招双龙

4.铁兽克拉斯块击链接神弓，发块击拿抗战

终场：

2400神弓+双龙+抗战+1手

1.似乎和combo13没什么差别


### combo15.姬特+2兽+2手：

1.通招姬特，姬特链接独角兔，发姬特扔纳贝尔，发纳贝尔拿克拉斯

2.特招克拉斯扔兽，发克拉斯特招块击

3.发块击扔兽特招姬特，发姬特特招双龙

4.克拉斯姬特块击链接神弓，发块击拿抗战

终场：

2400神弓+双龙+独角兔+抗战

1.打空手牌的做法，如果手牌质量好不建议使用，可换成combo28






### combo17.人马+铁兽+抗战：

1.发人马扔姬特，发姬特扔纳贝尔，发纳贝尔拿人马

2.通招人马，发人马特招徒花

3.发徒花特招铁兽，人马徒花链接银弹

4.发铁兽特招双龙，铁兽银弹链接神弓

终场：

1600神弓+双龙+抗战+2手



### combo18.人马+天玑+抗战：

1.发天玑拿羊冲，通招羊冲，羊冲叠猪弓，猪弓叠龙枪

2.发龙枪炸天玑，龙枪叠狗环，发狗环特招龙枪

3.狗环龙枪链接徒花，发徒花特招人马

4.发人马特招凶鸟，发人马扔姬特，发姬特扔纳贝尔，发纳贝尔拿克拉斯

5.徒花凶鸟链接银弹，发凶鸟拿马剑

6.特招克拉斯扔马剑，发克拉斯特招双龙，克拉斯银弹链接神弓

终场：

1600神弓+双龙+抗战+2手


### 纳贝尔+天玑+抗战：

1.发天玑拿羊冲，通招羊冲，羊冲叠猪弓，猪弓叠龙枪

2.发龙枪炸天玑，龙枪叠狗环，发狗环特招龙枪

3.狗环龙枪链接徒花，发徒花特招姬特/纳贝尔

4.特招凶鸟

5.徒花凶鸟链接银弹，发凶鸟拿马剑

6.银弹姬特/纳贝尔链接神弓, 姬特/纳贝尔拿克拉斯

7.特招克拉斯扔马剑，发克拉斯特招双龙

终场：

1600神弓+双龙+抗战+克拉斯+2手
 
# 4 

### ☆combo3.纳贝尔+马剑+羊冲+兽+1手：

1.通招马剑扔羊冲，马剑叠猪弓，猪弓叠狗环

2.发狗环特招羊冲，狗环叠龙枪

3.发龙枪炸羊冲，发羊冲特招狗环

4.龙枪叠虎炮，发虎炮指狗环，发狗环特招龙枪

5.狗环虎炮链接徒花，发徒花特招纳贝尔

6.发纳贝尔特招凶鸟，纳贝尔凶鸟链接块击，发纳贝尔拿克拉斯，发凶鸟拿蛇笞

7.特招克拉斯扔兽，发克拉斯特招双龙

8.克拉斯徒花块击链接神弓，发块击拿抗战，发蛇笞选龙枪

终场：

2400神弓+龙枪+双龙+抗战+1手

### combo4.克拉斯+姬特+十二兽+抗战：

1.通招十二兽，十二兽叠猪弓，猪弓叠龙枪

2.特招克拉斯扔姬特，发姬特扔纳贝尔，发纳贝尔拿人马

3.发克拉斯特招徒花，发龙枪炸克拉斯

4.龙枪叠狗环，发狗环特招龙枪，狗环叠虎炮，发虎炮选龙枪

5.发徒花特招人马，发人马特招双龙，人马虎炮徒花链接神弓

终场：

2400神弓+龙枪+双龙+抗战+1手

1.发克拉斯效果时，如果克拉斯被效遮泡影，连锁龙枪炸克拉斯可保效果通过

2.即使克拉斯没被无效，炸掉克拉斯可以丰富墓地资源，并启动十二兽的展开


 

 

# 5

### combo1.纳贝尔+马剑+羊冲+兽+抗战：

1.通招马剑扔羊冲，马剑叠猪弓，猪弓叠狗环

2.发狗环特招羊冲，狗环叠龙枪

3.发龙枪炸羊冲，发羊冲特招狗环  

4.龙枪叠虎炮，发虎炮指狗环，发狗环特招龙枪

5.狗环虎炮链接徒花，发徒花特招纳贝尔

6.发纳贝尔特招凶鸟，纳贝尔徒花凶鸟链接神弓，发纳贝尔拿克拉斯，发凶鸟拿蛇笞

7.特招克拉斯扔兽，发克拉斯特招双龙，发蛇笞选龙枪

终场：

2400神弓+龙枪+双龙+克拉斯+抗战+1手

1.发抗战前先发双龙释放场上克拉斯，这样空出3格子，可以通过纳贝尔姬特徒花来特招凶鸟

2.第7步用2手特招克拉斯+双龙可以视情况省略，留资源到下回合使用
